local CONFIG = {}

CONFIG.VERSION = "2.6.0"

CONFIG.WINDOW_TITLE = "tikrit"
CONFIG.WINDOW_WIDTH = 600
CONFIG.WINDOW_HEIGHT = 600
CONFIG.TILE_SIZE = 20
CONFIG.GRID_WIDTH = CONFIG.WINDOW_WIDTH / CONFIG.TILE_SIZE
CONFIG.GRID_HEIGHT = CONFIG.WINDOW_HEIGHT / CONFIG.TILE_SIZE

CONFIG.FONT_SIZE_LARGE = 80
CONFIG.FONT_SIZE_MEDIUM = 40
CONFIG.FONT_SIZE_SMALL = 22

CONFIG.PLAYER_BASE_SPEED = 200
CONFIG.PLAYER_SPEED_BUFF = 60
CONFIG.PLAYER_SPEED_BUFF_DURATION = 6
CONFIG.PLAYER_ATTACK_DAMAGE = 1
CONFIG.ATTACK_COOLDOWN = 0.75
CONFIG.ATTACK_RANGE = 34
CONFIG.ATTACK_ANIMATION_DURATION = 0.18
CONFIG.MONSTER_MAX_HEALTH = 3

CONFIG.VISION_BASE_RADIUS = 7
CONFIG.VISION_MIN_RADIUS = 2

CONFIG.MINIMAP_SIZE = 150
CONFIG.MINIMAP_SCALE = 0.25
CONFIG.MINIMAP_POSITION_X = 10
CONFIG.MINIMAP_POSITION_Y = 120
CONFIG.MINIMAP_BACKGROUND_ALPHA = 0.72

CONFIG.DIFFICULTY_SETTINGS = {
    easy = {
        playerSpeed = 230,
        monsterSpeed = 38,
        spawnBudget = 4,
        itemMultiplier = 1.4,
        visionBonus = 1,
        forcedFog = false,
        keyCount = 3,
    },
    normal = {
        playerSpeed = 200,
        monsterSpeed = 48,
        spawnBudget = 6,
        itemMultiplier = 1.0,
        visionBonus = 0,
        forcedFog = false,
        keyCount = 4,
    },
    hard = {
        playerSpeed = 185,
        monsterSpeed = 62,
        spawnBudget = 8,
        itemMultiplier = 0.8,
        visionBonus = -1,
        forcedFog = true,
        keyCount = 5,
    },
    nightmare = {
        playerSpeed = 165,
        monsterSpeed = 78,
        spawnBudget = 10,
        itemMultiplier = 0.65,
        visionBonus = -2,
        forcedFog = true,
        keyCount = 6,
    }
}

CONFIG.PROCGEN_MAX_DEPTH = 4
CONFIG.PROCGEN_MIN_ROOM_SIZE = 6
CONFIG.PROCGEN_MAX_ROOM_SIZE = 11
CONFIG.PROCGEN_CORRIDOR_PADDING = 1
CONFIG.PROCGEN_SAFE_ROOM_PADDING = 2
CONFIG.PROCGEN_DARK_ZONE_COUNT = 2
CONFIG.PROCGEN_RECOVERY_ROOM_COUNT = 1

CONFIG.SHRINE_RADIUS = 42
CONFIG.SAFE_ZONE_PADDING = 20

CONFIG.TIME_ATTACK_PAR_TIMES = {
    easy = 300,
    normal = 210,
    hard = 150,
    nightmare = 105,
}
CONFIG.TIME_ATTACK_SPEED_INCREASE_INTERVAL = 30
CONFIG.TIME_ATTACK_SPEED_INCREASE_AMOUNT = 4

CONFIG.MASTER_VOLUME = 0.7
CONFIG.AMBIENT_BASE_VOLUME = 0.28
CONFIG.GHOST_AUDIO_MAX_DISTANCE = 260
CONFIG.GHOST_AUDIO_MIN_DISTANCE = 40

CONFIG.PARTICLES_ENABLED = true
CONFIG.PARTICLE_COUNT_KEY = 16
CONFIG.PARTICLE_COUNT_ITEM = 14
CONFIG.PARTICLE_COUNT_DEATH = 26
CONFIG.PARTICLE_COUNT_DOOR = 10

CONFIG.SCREEN_SHAKE_INTENSITY = 5
CONFIG.SCREEN_SHAKE_DURATION = 0.25

CONFIG.GHOST_BOB_SPEED = 3
CONFIG.GHOST_BOB_AMOUNT = 3
CONFIG.CHEST_OPEN_DURATION = 0.28
CONFIG.DOOR_OPEN_DURATION = 0.35
CONFIG.PLAYER_IDLE_PULSE_SPEED = 2
CONFIG.PLAYER_IDLE_PULSE_AMOUNT = 0.02

CONFIG.SANITY_MAX = 100
CONFIG.SANITY_SAFE_DELAY = 4
CONFIG.SANITY_PASSIVE_RECOVERY = 3
CONFIG.SANITY_SHRINE_RECOVERY = 40
CONFIG.SANITY_KEY_RECOVERY = 10
CONFIG.SANITY_TONIC_RECOVERY = 28
CONFIG.SANITY_WARD_RECOVERY = 18
CONFIG.SANITY_DARK_ZONE_DRAIN = 6
CONFIG.SANITY_CREEPING_DRAIN = 1.5
CONFIG.SANITY_WAILER_DRAIN = 8
CONFIG.SANITY_STALKER_DRAIN = 4
CONFIG.SANITY_DETECTION_SPIKE = 20
CONFIG.SANITY_PANIC_SPEED_MULTIPLIER = 0.8
CONFIG.SANITY_PANIC_MONSTER_SPEED_MULTIPLIER = 1.18
CONFIG.SANITY_LOW_THRESHOLD = 75
CONFIG.SANITY_CRITICAL_THRESHOLD = 50
CONFIG.SANITY_BREAK_THRESHOLD = 25

CONFIG.INVENTORY_SIZE = 3

CONFIG.DEBUG_SHOW_COLLISION = false
CONFIG.DEBUG_SHOW_AI = false
CONFIG.DEBUG_SHOW_FPS = true

return CONFIG
