local CONFIG = {}

CONFIG.VERSION = "3.1.0"

CONFIG.WINDOW_TITLE = "tikrit"
CONFIG.WINDOW_WIDTH = 600
CONFIG.WINDOW_HEIGHT = 600
CONFIG.TILE_SIZE = 20
CONFIG.GRID_WIDTH = CONFIG.WINDOW_WIDTH / CONFIG.TILE_SIZE
CONFIG.GRID_HEIGHT = CONFIG.WINDOW_HEIGHT / CONFIG.TILE_SIZE

CONFIG.FONT_SIZE_LARGE = 72
CONFIG.FONT_SIZE_MEDIUM = 34
CONFIG.FONT_SIZE_SMALL = 18

CONFIG.DAY_DURATION_SECONDS = 360
CONFIG.GAME_HOURS_PER_REAL_SECOND = 24 / CONFIG.DAY_DURATION_SECONDS

CONFIG.PLAYER_WALK_SPEED = 95
CONFIG.PLAYER_SPRINT_SPEED = 150
CONFIG.PLAYER_OVERWEIGHT_SPEED = 72
CONFIG.PLAYER_BADLY_OVERWEIGHT_SPEED = 58

CONFIG.CARRY_CAPACITY = 25.0
CONFIG.BADLY_OVERWEIGHT_THRESHOLD = 7.0

CONFIG.MAX_CONDITION = 100
CONFIG.MAX_WARMTH = 100
CONFIG.MAX_FATIGUE = 100
CONFIG.MAX_THIRST = 100
CONFIG.MAX_CALORIES = 2500

CONFIG.VISIBLE_RADIUS_DAY = 7
CONFIG.VISIBLE_RADIUS_NIGHT = 4
CONFIG.VISIBLE_RADIUS_BLIZZARD = 2
CONFIG.VISIBLE_RADIUS_LIGHT_BONUS = 2
CONFIG.VISIBLE_RADIUS_SHELTER_BONUS = 1
CONFIG.VISIBLE_RADIUS_MAPPED_BONUS = 0.25

CONFIG.SHELTER_WARMTH_RECOVERY_PER_HOUR = 10
CONFIG.FIRE_WARMTH_RECOVERY_PER_HOUR = 28
CONFIG.NEAR_FIRE_DRY_RATE_PER_HOUR = 30
CONFIG.PASSIVE_DRY_RATE_PER_HOUR = 4
CONFIG.BED_WARMTH_RECOVERY_PER_HOUR = 14

CONFIG.THIRST_DRAIN_PER_HOUR = 3.2
CONFIG.CALORIE_DRAIN_PER_HOUR = 75
CONFIG.SPRINT_CALORIE_BONUS_PER_HOUR = 60
CONFIG.FATIGUE_DRAIN_PER_HOUR = 2.4
CONFIG.SPRINT_FATIGUE_BONUS_PER_HOUR = 3.6
CONFIG.OVERWEIGHT_FATIGUE_BONUS_PER_HOUR = 2.0

CONFIG.CONDITION_DRAIN_FREEZING_PER_HOUR = 8
CONFIG.CONDITION_DRAIN_THIRST_PER_HOUR = 6
CONFIG.CONDITION_DRAIN_STARVING_PER_HOUR = 5
CONFIG.CONDITION_RECOVERY_SLEEP_PER_HOUR = 6

CONFIG.WEAK_ICE_WARNING_HOURS = 0.10
CONFIG.WEAK_ICE_BREAK_CONDITION_DAMAGE = 10
CONFIG.WEAK_ICE_BREAK_WARMTH_DAMAGE = 100
CONFIG.WEAK_ICE_WETNESS_GAIN = 100

CONFIG.BLIZZARD_WETNESS_PER_HOUR = 16
CONFIG.SNOW_WETNESS_PER_HOUR = 6

CONFIG.FROSTBITE_WETNESS_THRESHOLD = 70
CONFIG.FROSTBITE_WARMTH_THRESHOLD = 25
CONFIG.FROSTBITE_RISK_PER_HOUR = 0.40
CONFIG.FROSTBITE_CONDITION_LOSS = 10

CONFIG.HYPOTHERMIA_RISK_WARMTH_THRESHOLD = 22
CONFIG.HYPOTHERMIA_RISK_PER_HOUR = 36
CONFIG.HYPOTHERMIA_RECOVERY_PER_HOUR = 22
CONFIG.HYPOTHERMIA_CONDITION_DRAIN_PER_HOUR = 4

CONFIG.SPRAIN_RISK_PER_HOUR = 12
CONFIG.SPRAIN_RECOVERY_HOURS = 3
CONFIG.SPRAIN_MOVE_PENALTY = 14

CONFIG.INFECTION_RISK_HOURS = 12
CONFIG.INFECTION_CONDITION_DRAIN_PER_HOUR = 4

CONFIG.FOOD_POISONING_HOURS = 10
CONFIG.FOOD_POISONING_CONDITION_DRAIN_PER_HOUR = 3
CONFIG.FOOD_POISONING_FATIGUE_DRAIN_PER_HOUR = 6

CONFIG.FIRE_BURN_HOURS = 3
CONFIG.FIRE_EMBERS_HOURS = 1
CONFIG.FIRE_ADD_FUEL_HOURS = 1.5
CONFIG.FIRE_HEAT_RADIUS_TILES = 4
CONFIG.FIRE_BASE_SUCCESS = 0.72
CONFIG.FIRE_WEATHER_PENALTY = {
    clear = 0.0,
    snow = 0.08,
    wind = 0.18,
    blizzard = 0.30,
}

CONFIG.WOLF_DETECTION_RADIUS_TILES = 7
CONFIG.WOLF_CHARGE_RADIUS_TILES = 3
CONFIG.WOLF_CONTACT_RADIUS_TILES = 0.9
CONFIG.WOLF_ROAM_SPEED = 26
CONFIG.WOLF_STALK_SPEED = 34
CONFIG.WOLF_CHARGE_SPEED = 70
CONFIG.WOLF_RETREAT_SPEED = 45
CONFIG.WOLF_FIRE_DETERRENCE_TILES = 5
CONFIG.WOLF_LIGHT_DETERRENCE_TILES = 3
CONFIG.WOLF_STRUGGLE_BASE_DAMAGE = 18

CONFIG.PASSIVE_FLEE_RADIUS_TILES = 2.4
CONFIG.ARROW_RANGE_TILES = 6
CONFIG.SNARE_CATCH_MIN_HOURS = 4
CONFIG.SNARE_CATCH_MAX_HOURS = 7
CONFIG.FISHING_ACTION_HOURS = 1.5
CONFIG.FISHING_BASE_CHANCE = 0.68
CONFIG.HARVEST_HOURS = {
    rabbit = 0.5,
    deer = 1.2,
    fish = 0.2,
}
CONFIG.CURING_HOURS = {
    rabbit_pelt = 12,
    deer_hide = 16,
    gut = 10,
}

CONFIG.ROPE_CLIMB_HOURS = 0.5
CONFIG.ROPE_CLIMB_FATIGUE_COST = 18
CONFIG.ROPE_CLIMB_CONDITION_COST = 4
CONFIG.MAP_REVEAL_RADIUS = 8
CONFIG.MAP_REVEAL_FATIGUE_COST = 4

CONFIG.SLEEP_REST_HOURS = 2
CONFIG.SNOW_SHELTER_STICK_COST = 6
CONFIG.SNOW_SHELTER_CLOTH_COST = 2
CONFIG.SNOW_SHELTER_DECAY_PER_HOUR = 3
CONFIG.SNOW_SHELTER_REPAIR_AMOUNT = 22
CONFIG.SNOW_SHELTER_REPAIR_STICKS = 2
CONFIG.SNOW_SHELTER_REPAIR_CLOTH = 1

CONFIG.CLOTHING_REPAIR_AMOUNT = 24
CONFIG.CLOTHING_UPGRADE_WARMTH = 3

CONFIG.RESOURCE_WOOD_MIN = 8
CONFIG.RESOURCE_WOOD_MAX = 12
CONFIG.RESOURCE_LOOT_MIN = 6
CONFIG.RESOURCE_LOOT_MAX = 8
CONFIG.WEAK_ICE_MIN = 6
CONFIG.WEAK_ICE_MAX = 10

CONFIG.SKILL_LEVEL_CAP = 5
CONFIG.SKILL_XP_PER_LEVEL = 25
CONFIG.SKILL_NAMES = {
    "FireStarting",
    "Cooking",
    "Fishing",
    "Harvesting",
    "Mending",
    "Archery",
}

CONFIG.DIFFICULTY_SETTINGS = {
    pilgrim = {
        exposureMultiplier = 0.75,
        thirstMultiplier = 0.85,
        calorieMultiplier = 0.85,
        fatigueMultiplier = 0.9,
        lootMultiplier = 1.35,
        wolfCount = 1,
        fireBonus = 0.12,
        hypothermiaMultiplier = 0.8,
        afflictionMultiplier = 0.8,
    },
    voyageur = {
        exposureMultiplier = 1.0,
        thirstMultiplier = 1.0,
        calorieMultiplier = 1.0,
        fatigueMultiplier = 1.0,
        lootMultiplier = 1.0,
        wolfCount = 1,
        fireBonus = 0.0,
        hypothermiaMultiplier = 1.0,
        afflictionMultiplier = 1.0,
    },
    stalker = {
        exposureMultiplier = 1.18,
        thirstMultiplier = 1.08,
        calorieMultiplier = 1.12,
        fatigueMultiplier = 1.1,
        lootMultiplier = 0.88,
        wolfCount = 2,
        fireBonus = -0.05,
        hypothermiaMultiplier = 1.12,
        afflictionMultiplier = 1.1,
    },
    interloper = {
        exposureMultiplier = 1.35,
        thirstMultiplier = 1.15,
        calorieMultiplier = 1.2,
        fatigueMultiplier = 1.18,
        lootMultiplier = 0.72,
        wolfCount = 2,
        fireBonus = -0.12,
        hypothermiaMultiplier = 1.22,
        afflictionMultiplier = 1.18,
    },
}

CONFIG.DIFFICULTY_ALIASES = {
    easy = "pilgrim",
    normal = "voyageur",
    hard = "stalker",
    nightmare = "interloper",
}

for legacyName, mappedName in pairs(CONFIG.DIFFICULTY_ALIASES) do
    CONFIG.DIFFICULTY_SETTINGS[legacyName] = CONFIG.DIFFICULTY_SETTINGS[mappedName]
end

CONFIG.WEATHER_ORDER = {"clear", "snow", "wind", "blizzard"}
CONFIG.WEATHER_TRANSITIONS = {
    clear = {"clear", "snow", "wind"},
    snow = {"clear", "snow", "wind", "blizzard"},
    wind = {"clear", "snow", "wind", "blizzard"},
    blizzard = {"snow", "wind", "blizzard"},
}
CONFIG.WEATHER_EXPOSURE_PER_HOUR = {
    clear = 6,
    snow = 10,
    wind = 13,
    blizzard = 22,
}
CONFIG.WEATHER_CHANGE_MIN_HOURS = 2
CONFIG.WEATHER_CHANGE_MAX_HOURS = 5

CONFIG.SCREEN_SHAKE_INTENSITY = 5
CONFIG.SCREEN_SHAKE_DURATION = 0.25

CONFIG.AMBIENT_BASE_VOLUME = 0.28

return CONFIG
